spring:
  datasource:
    # 使用数据库连接池druid（德鲁伊）
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-ehoahe42.sql.tencentcdb.com:22626/cms
    username: root
    password: WANGxing12345.

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
     banner: off # 关闭mybatisplus启动图标
     db-config:
    # 雪花算法全局设置
      id-type: auto #默认为assign_id
    # 前缀表名
      table-prefix: tbl_

      logic-delete-field: deleted
       # 逻辑删除字面值：未删除为0
      logic-not-delete-value: 0
       # 逻辑删除字面值：删除为1
      logic-delete-value: 1
server:
  port: 8989


